#:set colormid 0.45,0.45,0.45,1
#:set colorlabel "860b1d"
#:set bgcolor 0.9,0.9,0.9,1
#:set colordark 0.35,0.35,0.35,1
#:set textcolor 1,1,1,0.7
#:set cardtextcolor 1,0,0,1
#:set fontname "lcd/Digital7-rg1mL.ttf"
#:set font2 "lcd/Digital7-rg1mL.ttf"
#:set fontsize "30dp"
#:set textfontname "lcd/Digital7-rg1mL.ttf"
#:import Gradient kivy_gradient.Gradient
#:import get_color_from_hex kivy.utils.get_color_from_hex


<CreateAccount>:
<Deposite>:
    v: dd
    BoxLayout:
        orientation:
        orientation: 'horizontal'
        padding : ["60dp","40dp","5dp","30dp"]
        spacing: "10dp"
        canvas.before:
            Color:
                rgba:bgcolor
            Rectangle:
                pos:self.pos
                size:self.size
                texture:
                    Gradient.vertical(
                    get_color_from_hex("737373"), 
                    get_color_from_hex("8a8a8a"), 
                    get_color_from_hex("aeaeae")
                    )

        BoxLayout:
            id: left
            orientation: 'vertical'
            padding : ["20dp","10dp","20dp","30dp"]
            size_hint: 3.1, 1
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    texture:
                        Gradient.vertical(
                        get_color_from_hex("606060"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("383838"),
                        get_color_from_hex("383838"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("434343"), 
                        get_color_from_hex("383838")
                        )
                Color:
                    rgba:1,1,1,0.3
                Line:
                    width: dp(1)
                    rectangle: (*self.pos, self.width, self.height)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 3
                canvas.before:
                    Color:
                        rgba:colordark
                    Rectangle:
                        pos:self.pos
                        size:self.size
                    Color:
                        rgba:0.2,0.2,0.2,0.5
                    Line:
                        width: dp(2)
                        rectangle: (*self.pos, self.width, self.height)
                BoxLayout:
                    orientation: 'vertical'
                    padding : ["15dp","130dp","10dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("595959"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_1(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_2(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_3(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_4(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

                BoxLayout:
                    size_hint: 4.5, 1
                    orientation: 'vertical'
                    spacing:"0dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("3781b0"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("3781b0")
                                )
                    # AnchorLayout:
                    #     size_hint: 1,0.3
                    #     anchor_x: 'center'
                    #     anchor_y: 'center'
                    #     TextInput:
                    #         id: d
                    #         size_hint: 1,0.5
                    #         font_name: textfontname
                    #         font_size: fontsize
                    #         size_hint: None, None
                    #         size: 200, 50
                    #         hint_text:"card number"
                    #         hint_text_color: 1,1,1,0.5
                    #         multiline : False
                    #         background_color: 0,0,0.3,0.5
                    #         foreground_color: 1,1,1,1
                    #         on_text_validate: root.on_enter()   
                    AnchorLayout:
                        size_hint: 1,0.3
                        anchor_x: 'center'
                        anchor_y: 'center'
                        TextInput:
                            id: dd
                            font_name: textfontname
                            font_size: fontsize
                            size_hint: None, None
                            size: 200, 50
                            hint_text:"amount"
                            hint_text_color: 1,1,1,0.5
                            multiline : False
                            background_color: 0,0,0.3,0.5
                            foreground_color: 1,1,1,1
                            on_text_validate: root.on_enter()                    

                    GridLayout:
                        cols:2
                        padding : ["0dp","0dp","0dp","5dp"]
                        spacing: "20dp"
                        Label:
                            text: root.text1
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:

                            text: root.text5
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text2
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text6
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text3
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text7
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 1.5
                        Label:
                            text: root.text4
                            color: textcolor
                            font_name: fontname  
                            font_size: self.height / 1.5               
                        Label:
                            text: root.text8
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 1.5


                BoxLayout:
                    orientation: 'vertical'
                    padding : ["10dp","130dp","15dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("595959")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_5(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                        # on_press: root.manager.current = 'mw'
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_6(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_7(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_8(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

    #cash_layout
            BoxLayout:
                padding : ["100dp","20dp","100dp","30dp"]
                spacing: "20dp"
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba:1,1,1,0.5
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("383838"), 
                            get_color_from_hex("656565"), 
                            get_color_from_hex("707070"), 
                            get_color_from_hex("aaaaaa")
                            )
                    Color:
                        rgba:0.9,0.9,0.9,0.1
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CASH"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.7
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_top
        BoxLayout:
            id: right
            orientation: 'vertical'
            padding : ["20dp","40dp","20dp","30dp"]
            spacing: "40dp"
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "RECEIPT"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("950b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_bot
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CARD"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("800b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height

<Withdraw>:
    v: dd
    BoxLayout:
        orientation:
        orientation: 'horizontal'
        padding : ["60dp","40dp","5dp","30dp"]
        spacing: "10dp"
        canvas.before:
            Color:
                rgba:bgcolor
            Rectangle:
                pos:self.pos
                size:self.size
                texture:
                    Gradient.vertical(
                    get_color_from_hex("737373"), 
                    get_color_from_hex("8a8a8a"), 
                    get_color_from_hex("aeaeae")
                    )

        BoxLayout:
            id: left
            orientation: 'vertical'
            padding : ["20dp","10dp","20dp","30dp"]
            size_hint: 3.1, 1
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    texture:
                        Gradient.vertical(
                        get_color_from_hex("606060"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("383838"),
                        get_color_from_hex("383838"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("434343"), 
                        get_color_from_hex("383838")
                        )
                Color:
                    rgba:1,1,1,0.3
                Line:
                    width: dp(1)
                    rectangle: (*self.pos, self.width, self.height)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 3
                canvas.before:
                    Color:
                        rgba:colordark
                    Rectangle:
                        pos:self.pos
                        size:self.size
                    Color:
                        rgba:0.2,0.2,0.2,0.5
                    Line:
                        width: dp(2)
                        rectangle: (*self.pos, self.width, self.height)
                BoxLayout:
                    orientation: 'vertical'
                    padding : ["15dp","130dp","10dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("595959"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_1(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_2(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_3(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_4(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

                BoxLayout:
                    size_hint: 4.5, 1
                    orientation: 'vertical'
                    spacing:"0dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("3781b0"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("3781b0")
                                )
                    # AnchorLayout:
                    #     size_hint: 1,0.3
                    #     anchor_x: 'center'
                    #     anchor_y: 'center'
                    #     TextInput:
                    #         id: d
                    #         size_hint: 1,0.5
                    #         font_name: textfontname
                    #         font_size: fontsize
                    #         size_hint: None, None
                    #         size: 200, 50
                    #         hint_text:"card number"
                    #         hint_text_color: 1,1,1,0.5
                    #         multiline : False
                    #         background_color: 0,0,0.3,0.5
                    #         foreground_color: 1,1,1,1
                    #         on_text_validate: root.on_enter()   
                    AnchorLayout:
                        size_hint: 1,0.3
                        anchor_x: 'center'
                        anchor_y: 'center'
                        TextInput:
                            id: dd
                            font_name: textfontname
                            font_size: fontsize
                            size_hint: None, None
                            size: 200, 50
                            hint_text:"amount"
                            hint_text_color: 1,1,1,0.5
                            multiline : False
                            background_color: 0,0,0.3,0.5
                            foreground_color: 1,1,1,1
                            on_text_validate: root.on_enter()                    

                    GridLayout:
                        cols:2
                        padding : ["0dp","0dp","0dp","5dp"]
                        spacing: "20dp"
                        Label:
                            text: root.text1
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:

                            text: root.text5
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text2
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text6
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text3
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text7
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 1.5
                        Label:
                            text: root.text4
                            color: textcolor
                            font_name: fontname  
                            font_size: self.height / 1.5               
                        Label:
                            text: root.text8
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 1.5


                BoxLayout:
                    orientation: 'vertical'
                    padding : ["10dp","130dp","15dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("595959")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_5(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                        # on_press: root.manager.current = 'mw'
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_6(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_7(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_8(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

    #cash_layout
            BoxLayout:
                padding : ["100dp","20dp","100dp","30dp"]
                spacing: "20dp"
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba:1,1,1,0.5
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("383838"), 
                            get_color_from_hex("656565"), 
                            get_color_from_hex("707070"), 
                            get_color_from_hex("aaaaaa")
                            )
                    Color:
                        rgba:0.9,0.9,0.9,0.1
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CASH"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.7
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_top
        BoxLayout:
            id: right
            orientation: 'vertical'
            padding : ["20dp","40dp","20dp","30dp"]
            spacing: "40dp"
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "RECEIPT"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("950b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_bot
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CARD"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("800b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
<Transfer>:
    inp: d
    v: dd
    BoxLayout:
        orientation:
        orientation: 'horizontal'
        padding : ["60dp","40dp","5dp","30dp"]
        spacing: "10dp"
        canvas.before:
            Color:
                rgba:bgcolor
            Rectangle:
                pos:self.pos
                size:self.size
                texture:
                    Gradient.vertical(
                    get_color_from_hex("737373"), 
                    get_color_from_hex("8a8a8a"), 
                    get_color_from_hex("aeaeae")
                    )

        BoxLayout:
            id: left
            orientation: 'vertical'
            padding : ["20dp","10dp","20dp","30dp"]
            size_hint: 3.1, 1
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    texture:
                        Gradient.vertical(
                        get_color_from_hex("606060"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("383838"),
                        get_color_from_hex("383838"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("434343"), 
                        get_color_from_hex("383838")
                        )
                Color:
                    rgba:1,1,1,0.3
                Line:
                    width: dp(1)
                    rectangle: (*self.pos, self.width, self.height)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 3
                canvas.before:
                    Color:
                        rgba:colordark
                    Rectangle:
                        pos:self.pos
                        size:self.size
                    Color:
                        rgba:0.2,0.2,0.2,0.5
                    Line:
                        width: dp(2)
                        rectangle: (*self.pos, self.width, self.height)
                BoxLayout:
                    orientation: 'vertical'
                    padding : ["15dp","130dp","10dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("595959"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_1(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_2(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_3(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_4(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

                BoxLayout:
                    size_hint: 4.5, 1
                    orientation: 'vertical'
                    spacing:"0dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("3781b0"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("3781b0")
                                )
                    AnchorLayout:
                        size_hint: 1,0.3
                        anchor_x: 'center'
                        anchor_y: 'center'
                        TextInput:
                            id: d
                            size_hint: 1,0.5
                            font_name: textfontname
                            font_size: fontsize
                            size_hint: None, None
                            size: 200, 50
                            hint_text:"card number"
                            hint_text_color: 1,1,1,0.5
                            multiline : False
                            background_color: 0,0,0.3,0.5
                            foreground_color: 1,1,1,1
                            on_text_validate: root.on_enter()   
                    AnchorLayout:
                        size_hint: 1,0.3
                        anchor_x: 'center'
                        anchor_y: 'center'
                        TextInput:
                            id: dd
                            font_name: textfontname
                            font_size: fontsize
                            size_hint: None, None
                            size: 200, 50
                            hint_text:"amount"
                            hint_text_color: 1,1,1,0.5
                            multiline : False
                            background_color: 0,0,0.3,0.5
                            foreground_color: 1,1,1,1
                            on_text_validate: root.on_enter()                    

                    GridLayout:
                        cols:2
                        padding : ["0dp","0dp","0dp","5dp"]
                        spacing: "20dp"
                        Label:
                            text: root.text1
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:

                            text: root.text5
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text2
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text6
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text3
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text7
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 1.5
                        Label:
                            text: root.text4
                            color: textcolor
                            font_name: fontname  
                            font_size: self.height / 1.5               
                        Label:
                            text: root.text8
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 1.5


                BoxLayout:
                    orientation: 'vertical'
                    padding : ["10dp","130dp","15dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("595959")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_5(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                        # on_press: root.manager.current = 'mw'
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_6(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_7(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_8(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

    #cash_layout
            BoxLayout:
                padding : ["100dp","20dp","100dp","30dp"]
                spacing: "20dp"
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba:1,1,1,0.5
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("383838"), 
                            get_color_from_hex("656565"), 
                            get_color_from_hex("707070"), 
                            get_color_from_hex("aaaaaa")
                            )
                    Color:
                        rgba:0.9,0.9,0.9,0.1
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CASH"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.7
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_top
        BoxLayout:
            id: right
            orientation: 'vertical'
            padding : ["20dp","40dp","20dp","30dp"]
            spacing: "40dp"
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "RECEIPT"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("950b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_bot
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CARD"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("800b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height

<LogIn>:
    inp: d
    BoxLayout:
        orientation:
        orientation: 'horizontal'
        padding : ["60dp","40dp","5dp","30dp"]
        spacing: "10dp"
        canvas.before:
            Color:
                rgba:bgcolor
            Rectangle:
                pos:self.pos
                size:self.size
                texture:
                    Gradient.vertical(
                    get_color_from_hex("737373"), 
                    get_color_from_hex("8a8a8a"), 
                    get_color_from_hex("aeaeae")
                    )

        BoxLayout:
            id: left
            orientation: 'vertical'
            padding : ["20dp","10dp","20dp","30dp"]
            size_hint: 3.1, 1
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    texture:
                        Gradient.vertical(
                        get_color_from_hex("606060"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("383838"),
                        get_color_from_hex("383838"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("434343"), 
                        get_color_from_hex("383838")
                        )
                Color:
                    rgba:1,1,1,0.3
                Line:
                    width: dp(1)
                    rectangle: (*self.pos, self.width, self.height)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 3
                canvas.before:
                    Color:
                        rgba:colordark
                    Rectangle:
                        pos:self.pos
                        size:self.size
                    Color:
                        rgba:0.2,0.2,0.2,0.5
                    Line:
                        width: dp(2)
                        rectangle: (*self.pos, self.width, self.height)
                BoxLayout:
                    orientation: 'vertical'
                    padding : ["15dp","130dp","10dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("595959"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_1(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_2(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_3(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_4(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

                BoxLayout:
                    size_hint: 4.5, 1
                    orientation: 'vertical'
                    spacing:"0dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("3781b0"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("3781b0")
                                )
                    Label:
                        size_hint: 1,0.5
                        text: 'Enter Password'
                        color: textcolor
                        font_name: fontname
                        font_size: self.height / 4
                    AnchorLayout:
                        size_hint: 1,0.3
                        anchor_x: 'center'
                        anchor_y: 'center'
                        TextInput:
                            id: d
                            font_name: textfontname
                            font_size: fontsize
                            size_hint: None, None
                            size: 100, 50
                            hint_text:"_ _ _ _"
                            hint_text_color: 1,1,1,0.5
                            password : True
                            multiline : False
                            background_color: 0,0,0.3,0
                            foreground_color: 1,1,1,1
                            on_text_validate: root.on_enter()                    

                    GridLayout:
                        cols:2
                        padding : ["0dp","0dp","0dp","5dp"]
                        spacing: "20dp"
                        Label:
                            text: root.text1
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:

                            text: root.text5
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text2
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text6
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text3
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text7
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text4
                            color: textcolor
                            font_name: fontname  
                            font_size: self.height / 1.5               
                        Label:
                            text: root.text8
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 1.5


                BoxLayout:
                    orientation: 'vertical'
                    padding : ["10dp","130dp","15dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("595959")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_5(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                        # on_press: root.manager.current = 'mw'
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_6(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_7(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_8(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

    #cash_layout
            BoxLayout:
                padding : ["100dp","20dp","100dp","30dp"]
                spacing: "20dp"
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba:1,1,1,0.5
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("383838"), 
                            get_color_from_hex("656565"), 
                            get_color_from_hex("707070"), 
                            get_color_from_hex("aaaaaa")
                            )
                    Color:
                        rgba:0.9,0.9,0.9,0.1
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CASH"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.7
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_top
        BoxLayout:
            id: right
            orientation: 'vertical'
            padding : ["20dp","40dp","20dp","30dp"]
            spacing: "40dp"
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "RECEIPT"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("950b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_bot
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CARD"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("800b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
<Card>:
    inp : d
    BoxLayout:
        orientation:
        orientation: 'horizontal'
        padding : ["60dp","40dp","5dp","30dp"]
        spacing: "10dp"
        canvas.before:
            Color:
                rgba:bgcolor
            Rectangle:
                pos:self.pos
                size:self.size
                texture:
                    Gradient.vertical(
                    get_color_from_hex("737373"), 
                    get_color_from_hex("8a8a8a"), 
                    get_color_from_hex("aeaeae")
                    )
        BoxLayout:
            id: left
            orientation: 'vertical'
            padding : ["20dp","10dp","20dp","30dp"]
            size_hint: 3.1, 1
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    texture:
                        Gradient.vertical(
                        get_color_from_hex("606060"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("383838"),
                        get_color_from_hex("383838"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("434343"), 
                        get_color_from_hex("383838")
                        )
                Color:
                    rgba:1,1,1,0.3
                Line:
                    width: dp(1)
                    rectangle: (*self.pos, self.width, self.height)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 3
                canvas.before:
                    Color:
                        rgba:colordark
                    Rectangle:
                        pos:self.pos
                        size:self.size
                    Color:
                        rgba:0.2,0.2,0.2,0.5
                    Line:
                        width: dp(2)
                        rectangle: (*self.pos, self.width, self.height)
                BoxLayout:
                    orientation: 'vertical'
                    padding : ["15dp","130dp","10dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("595959"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

                BoxLayout:
                    size_hint: 4.5, 1
                    orientation: 'vertical'
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("3781b0"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("3781b0")
                                )
                    Label:
                        size_hint: 1,0.5
                        text: 'welcome to 2+2=5 bank\ndo you have an account?'
                        color: get_color_from_hex("d9d185")
                        font_name: fontname
                        font_size: self.height / 4

                    GridLayout:
                        cols:2
                        Label:
                            text: 'welcome'
                        Label:
                            text: 'welcome'
                        Label:
                            text: 'welcome'
                        Label:
                            text: 'welcome'
                        Label:
                            text: 'welcome'
                        Label:
                            text: 'welcome'
                        Label:
                            text: '<-- no'
                            color: textcolor
                            font_name: fontname  
                            font_size: self.height / 2               
                        Label:
                            text: 'yes -->'
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2


                BoxLayout:
                    orientation: 'vertical'
                    padding : ["10dp","130dp","15dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("595959")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                        on_press: root.manager.current = 'mw'
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

    #cash_layout
            BoxLayout:
                padding : ["100dp","20dp","100dp","30dp"]
                spacing: "20dp"
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba:1,1,1,0.5
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("383838"), 
                            get_color_from_hex("656565"), 
                            get_color_from_hex("707070"), 
                            get_color_from_hex("aaaaaa")
                            )
                    Color:
                        rgba:0.9,0.9,0.9,0.1
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CASH"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.7
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_top
        BoxLayout:
            id: right
            orientation: 'vertical'
            padding : ["20dp","40dp","20dp","30dp"]
            spacing: "40dp"
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "RECEIPT"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("950b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_bot
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CARD"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("800b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height

    Image:
        pos: 0,100
        source:"img/kh.png"
    Image:
        pos: 0,-100
        source:"img/pngwing.co.png"
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        AnchorLayout:
            Image:
                source: "img/card.PNG"
                size_hint: None, None
                size: 400, 400
            BoxLayout:
                orientation: "vertical"
                size_hint: None, None
                padding : ["20dp","0dp","20dp","110dp"]
                spacing: "40dp"
                size: 400, 300
                Label:
                    font_name: textfontname
                    font_size: "50dp"
                    size_hint: 1, 1
                    text: "2+2=5"
                TextInput:
                    id: d
                    font_name: textfontname
                    font_size: fontsize
                    size_hint: 1, 0.5
                    size: 350, 50
                    hint_text:"enter card number"
                    multiline : False
                    background_color: 0,0,0.3,0.5
                    foreground_color: 1,1,1,1
                    line_spacing : 10
                    on_text_validate: root.on_enter()
                # Label:
                #     font_name: textfontname
                #     font_size: fontsize
                #     size_hint: 0.4, 1
                #     text: "cvv2:8008"

    AnchorLayout:
        anchor_x: 'right'
        anchor_y: 'bottom'
        Button:
            on_press : root.manager.current = 'rootpage'
            text: 'back'

            color: 1, 1, 1, 1
            size_hint: None, None
            size: 100, 100






<mainmenu>:
    BoxLayout:
        orientation:
        orientation: 'horizontal'
        padding : ["60dp","40dp","5dp","30dp"]
        spacing: "10dp"
        canvas.before:
            Color:
                rgba:bgcolor
            Rectangle:
                pos:self.pos
                size:self.size
                texture:
                    Gradient.vertical(
                    get_color_from_hex("737373"), 
                    get_color_from_hex("8a8a8a"), 
                    get_color_from_hex("aeaeae")
                    )

        BoxLayout:
            id: left
            orientation: 'vertical'
            padding : ["20dp","10dp","20dp","30dp"]
            size_hint: 3.1, 1
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    texture:
                        Gradient.vertical(
                        get_color_from_hex("606060"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("383838"),
                        get_color_from_hex("383838"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("434343"), 
                        get_color_from_hex("383838")
                        )
                Color:
                    rgba:1,1,1,0.3
                Line:
                    width: dp(1)
                    rectangle: (*self.pos, self.width, self.height)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 3
                canvas.before:
                    Color:
                        rgba:colordark
                    Rectangle:
                        pos:self.pos
                        size:self.size
                    Color:
                        rgba:0.2,0.2,0.2,0.5
                    Line:
                        width: dp(2)
                        rectangle: (*self.pos, self.width, self.height)
                BoxLayout:
                    orientation: 'vertical'
                    padding : ["15dp","130dp","10dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("595959"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_1(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_2(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_3(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_4(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

                BoxLayout:
                    size_hint: 4.5, 1
                    orientation: 'vertical'
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("3781b0"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("3781b0")
                                )
                        # Color:
                        #     rgba:0,0,0,1
                        # Line:
                        #     width: dp(1)
                        #     rectangle: (*self.pos, self.width, self.height)
                    Label:
                        size_hint: 1,0.5
                        text: 'choose'
                        color: textcolor
                        font_name: fontname
                        font_size: self.height / 4

                    GridLayout:
                        cols:2
                        padding : ["0dp","0dp","0dp","5dp"]
                        spacing: "20dp"
                        Label:
                            text: root.text1
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:

                            text: root.text5
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text2
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text6
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text3
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text7
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text4
                            color: textcolor
                            font_name: fontname  
                            font_size: self.height / 2               
                        Label:
                            text: root.text8
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2


                BoxLayout:
                    orientation: 'vertical'
                    padding : ["10dp","130dp","15dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("595959")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_5(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                        # on_press: root.manager.current = 'mw'
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_6(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_7(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_8(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

    #cash_layout
            BoxLayout:
                padding : ["100dp","20dp","100dp","30dp"]
                spacing: "20dp"
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba:1,1,1,0.5
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("383838"), 
                            get_color_from_hex("656565"), 
                            get_color_from_hex("707070"), 
                            get_color_from_hex("aaaaaa")
                            )
                    Color:
                        rgba:0.9,0.9,0.9,0.1
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CASH"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.7
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_top
        BoxLayout:
            id: right
            orientation: 'vertical'
            padding : ["20dp","40dp","20dp","30dp"]
            spacing: "40dp"
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "RECEIPT"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("950b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_bot
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CARD"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("800b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
<firstpage>:
    BoxLayout:
        orientation:
        orientation: 'horizontal'
        padding : ["60dp","40dp","5dp","30dp"]
        spacing: "10dp"
        canvas.before:
            Color:
                rgba:bgcolor
            Rectangle:
                pos:self.pos
                size:self.size
                texture:
                    Gradient.vertical(
                    get_color_from_hex("737373"), 
                    get_color_from_hex("8a8a8a"), 
                    get_color_from_hex("aeaeae")
                    )

        BoxLayout:
            id: left
            orientation: 'vertical'
            padding : ["20dp","10dp","20dp","30dp"]
            size_hint: 3.1, 1
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    pos:self.pos
                    size:self.size
                    texture:
                        Gradient.vertical(
                        get_color_from_hex("606060"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("383838"),
                        get_color_from_hex("383838"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("454545"), 
                        get_color_from_hex("434343"), 
                        get_color_from_hex("383838")
                        )
                Color:
                    rgba:1,1,1,0.3
                Line:
                    width: dp(1)
                    rectangle: (*self.pos, self.width, self.height)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 3
                canvas.before:
                    Color:
                        rgba:colordark
                    Rectangle:
                        pos:self.pos
                        size:self.size
                    Color:
                        rgba:0.2,0.2,0.2,0.5
                    Line:
                        width: dp(2)
                        rectangle: (*self.pos, self.width, self.height)
                BoxLayout:
                    orientation: 'vertical'
                    padding : ["15dp","130dp","10dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("595959"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_1(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_2(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_3(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_4(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

                BoxLayout:
                    size_hint: 4.5, 1
                    orientation: 'vertical'
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("3781b0"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("6a9cc4"), 
                                get_color_from_hex("3781b0")
                                )
                        # Color:
                        #     rgba:0,0,0,1
                        # Line:
                        #     width: dp(1)
                        #     rectangle: (*self.pos, self.width, self.height)
                    Label:
                        size_hint: 1,0.5
                        text: 'welcome to 2+2=5 bank\ndo you have an account?'
                        color: textcolor
                        font_name: fontname
                        font_size: self.height / 4

                    GridLayout:
                        cols:2
                        padding : ["0dp","0dp","0dp","5dp"]
                        spacing: "20dp"
                        Label:
                            text: root.text1
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:

                            text: root.text5
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text2
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text6
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text3
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text7
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2
                        Label:
                            text: root.text4
                            color: textcolor
                            font_name: fontname  
                            font_size: self.height / 2               
                        Label:
                            text: root.text8
                            color: textcolor
                            font_name: fontname
                            font_size: self.height / 2


                BoxLayout:
                    orientation: 'vertical'
                    padding : ["10dp","130dp","15dp","10dp"]
                    spacing: "10dp"
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.horizontal(
                                get_color_from_hex("656565"), 
                                get_color_from_hex("707070"), 
                                get_color_from_hex("656565"), 
                                get_color_from_hex("595959")
                                )
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_5(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                        # on_press: root.manager.current = 'mw'
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_6(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_7(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)
                    Button:
                        background_color: (42/88 , 42/88 , 42/88)
                        size_hint: 1, 0.7
                        on_press: root.on_button_8(self)
                        canvas.before:
                            Color:
                                rgba:0.9,0.9,0.9,0.5
                            Line:
                                width: dp(1)
                                rectangle: (*self.pos, self.width, self.height)

    #cash_layout
            BoxLayout:
                padding : ["100dp","20dp","100dp","30dp"]
                spacing: "20dp"
                orientation: 'vertical'
                canvas.before:
                    Color:
                        rgba:1,1,1,0.5
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("383838"), 
                            get_color_from_hex("656565"), 
                            get_color_from_hex("707070"), 
                            get_color_from_hex("aaaaaa")
                            )
                    Color:
                        rgba:0.9,0.9,0.9,0.1
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CASH"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.7
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_top
        BoxLayout:
            id: right
            orientation: 'vertical'
            padding : ["20dp","40dp","20dp","30dp"]
            spacing: "40dp"
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "RECEIPT"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("950b1d") ,
                                get_color_from_hex("900b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height
    #right_bot
            BoxLayout:
                id: top_right
                orientation: 'vertical'
                padding : ["20dp","10dp","20dp","115dp"]
                spacing: "30dp"
                canvas.before:
                    Color:
                        rgba:1,1,1,0.3
                    Rectangle:
                        pos:self.pos
                        size:self.size
                        texture:
                            Gradient.vertical(
                            get_color_from_hex("303030"), 
                            get_color_from_hex("404040") ,
                            get_color_from_hex("202020"),
                            get_color_from_hex("c1c1c1"), 
                            get_color_from_hex("929292")
                            )
                    Color:
                        rgba:0,0,0,0.5
                    Line:
                        width: dp(1)
                        rectangle: (*self.pos, self.width, self.height)
                Label:
                    text: "CARD"
                    color: cardtextcolor
                    font_name: font2
                    canvas.before:
                        Color:
                            rgba:1,1,1,1
                        Rectangle:
                            pos:self.pos
                            size:self.size
                            texture:
                                Gradient.vertical(
                                get_color_from_hex("700b1d"), 
                                get_color_from_hex("800b1d") ,
                                get_color_from_hex("860b1d") ,
                                get_color_from_hex("800b1d")
                                )
                        Color:
                            rgba:0.1,0,0,0.5
                        Line:
                            width: dp(1)
                            rectangle: (*self.pos, self.width, self.height)
                Button:
                    background_color: (32/88 , 32/88 , 32/88)
                    size_hint: 1, 0.5
                    canvas.before:
                        Color:
                            rgba: .6, .6, .6, 1
                        Line:
                            width: 2
                            rectangle: self.x, self.y, self.width, self.height